# Generated by Django 2.0.7 on 2018-09-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=25)),
                ('last', models.CharField(blank=True, max_length=25)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('social', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venues', models.CharField(max_length=100)),
                ('trained', models.IntegerField(max_length=10)),
                ('male', models.IntegerField(max_length=10)),
                ('female', models.IntegerField(max_length=10)),
                ('report', models.CharField(max_length=100)),
                ('recommendation', models.CharField(max_length=100)),
            ],
        ),
    ]
