# Generated by Django 2.0.7 on 2018-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='female',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='male',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trained',
            field=models.IntegerField(),
        ),
    ]
