# Generated by Django 2.0.7 on 2018-09-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0003_auto_20180913_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-18T15:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='post',
            field=models.ForeignKey(default='post_id', on_delete=django.db.models.deletion.CASCADE, to='my_post.Post'),
            preserve_default=False,
        ),
    ]
