# Generated by Django 2.0.7 on 2018-09-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0002_auto_20180913_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='social',
            new_name='social_media',
        ),
    ]
